### ISSUE TITLE
Attempting to run command in a container raises Java Exception

### ISSUE THREAD

**Issue by Melkaz** [kestra-io/plugin-azure#18]
### Expected Behavior

Should run my command in a container, on Azure Batch.

### Actual Behaviour

```
INFO     2022-12-01 15:00:51.743Job 'test-azure-batch-cpu-jobX' created on poll '[REDACTED]'
TRACE    2022-12-01 15:00:51.803java.lang.NullPointerException
	at io.kestra.plugin.azure.batch.models.TaskContainerSettings.to(TaskContainerSettings.java:51)
	at io.kestra.plugin.azure.batch.models.Task.to(Task.java:133)
	at io.kestra.plugin.azure.batch.job.Create.run(Create.java:123)
	at io.kestra.plugin.azure.batch.job.Create.run(Create.java:37)
	at io.kestra.core.runners.Worker$WorkerThread.run(Worker.java:499)
```

### Environment Information

- Kestra Version: 0.5.3-SNAPSHOT

### Example flow

```
id: test-azure-batch
namespace: io.kestra.flows.azure
description: |
  Run test commands on AzureBatch

variables:
  azureBatch:
    accessKey: [REDACTED]
    account: [REDACTED]
    endpoint: https://[REDACTED].batch.azure.com
    pools:
      cpuSmall: [REDACTED]

tasks:
  - id: AZ-echo
    type: io.kestra.plugin.azure.batch.job.Create
    accessKey: "{{ vars.azureBatch.accessKey }}"
    account: "{{ vars.azureBatch.account }}"
    endpoint: "{{ vars.azureBatch.endpoint }}"
    poolId: "{{ vars.azureBatch.pools.cpuSmall }}"
    job:
      id: test-azure-batch-cpu-jobX
    tasks:
      - id: echo
        commandLine: /bin/bash -c 'echo Hello World!'
        containerSettings:
          imageName: ubuntu:20.04
```

**Comment by Melkaz** [comment]
It seems that some properties, while described as having default values are needed.

Here is my task within the `io.kestra.plugin.azure.batch.job.Create` `tasks` property:

```
id: echo
commandLine: /bin/bash -c 'echo Hello World!'
containerSettings:
  imageName: ubuntu:20.04
  registry:
    registryServer: docker.io
    identityReference:
      resourceId: admin
```
Using this gets rid of the Java error, but the job never seems to run on AzureBatch side.

**Comment by tchiotludo** [comment]
It was fixed on this https://github.com/kestra-io/plugin-azure/commit/5c6a5a7ea36f5d0099b69fd2f0b6d58396df06f4, reopen if not

**Comment by Melkaz** [comment]
Fixed, thanks Ludo !
