### ISSUE TITLE
StorageBlob List task resulting into error

### ISSUE THREAD

**Issue by shrutimantri** [kestra-io/plugin-azure#70]
### Expected Behavior

The StorageBlob List task should list all the blobs within a container under a given prefix.

### Actual Behaviour

The List task results in the following error:

```
2024-02-17 12:19:28.059Cannot invoke "com.azure.storage.blob.implementation.models.BlobItemPropertiesInternal.getContentType()" because "this.internalProperties" is null
2024-02-17 12:19:28.059java.lang.NullPointerException: Cannot invoke "com.azure.storage.blob.implementation.models.BlobItemPropertiesInternal.getContentType()" because "this.internalProperties" is null
	at com.azure.storage.blob.models.BlobItemProperties.getContentType(BlobItemProperties.java:141)
	at io.kestra.plugin.azure.storage.blob.services.BlobService.filter(BlobService.java:121)
	at io.kestra.plugin.azure.storage.blob.services.BlobService.lambda$list$0(BlobService.java:111)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.base/java.util.Iterator.forEachRemaining(Unknown Source)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
	at io.kestra.plugin.azure.storage.blob.services.BlobService.list(BlobService.java:113)
	at io.kestra.plugin.azure.storage.blob.List.run(List.java:58)
	at io.kestra.plugin.azure.storage.blob.List.run(List.java:19)
	at io.kestra.core.runners.Worker$WorkerThread.run(Worker.java:684)
```

### Steps To Reproduce

1. Use the flow example as present on this [page](https://kestra.io/plugins/plugin-azure/tasks/storage.blob/io.kestra.plugin.azure.storage.blob.List)
2. Flow:
```
id: "list"
type: "io.kestra.plugin.azure.storage.blob.List"
endpoint: "https://yourblob.blob.core.windows.net"
connectionString: "DefaultEndpointsProtocol=...=="
container: "mydata"
prefix: "sub-dir"
delimiter: "/"
```
3. Put appropriate values and run the example. 

### Environment Information

- Kestra Version: 0.13.8
- Plugin version: 0.13.8
- Operating System (OS / Docker / Kubernetes): Docker
- Java Version (If not docker): N/A

### Example flow

```
id: "list"
type: "io.kestra.plugin.azure.storage.blob.List"
endpoint: "https://yourblob.blob.core.windows.net"
connectionString: "DefaultEndpointsProtocol=...=="
container: "mydata"
prefix: "sub-dir"
delimiter: "/"
```

**Comment by cedrelek** [comment]
@anna-geller Here an easy fix :

Replace this test :

https://github.com/kestra-io/plugin-azure/blob/aecb93d1f3355549ca3e1ef6b5480ac91a4f6b47/src/main/java/io/kestra/plugin/azure/storage/blob/services/BlobService.java#L124
by
`(filter == ListInterface.Filter.DIRECTORY && object.isPrefix()) ||`

And 
https://github.com/kestra-io/plugin-azure/blob/aecb93d1f3355549ca3e1ef6b5480ac91a4f6b47/src/main/java/io/kestra/plugin/azure/storage/blob/services/BlobService.java#L125
by 
`(filter == ListInterface.Filter.FILES && !object.isPrefix())

`object.getProperties().getContentType()` throws a null pointer when the blob item is a prefix, because a prefix does not have properties.

@shrutimantri use Filter.BOTH to prevent the checks of null properties.

**Comment by Ben8t** [comment]
Able to reproduce. FYI the task work when no prefix or sub-dir is passed

(_this one doesn't work as mentioned in the issue_)
```yaml
id: test-azure-blog
namespace: company.team
tasks:
  
  - id: "list"
    type: "io.kestra.plugin.azure.storage.blob.List"
    endpoint: "https://kestrademo.blob.core.windows.net"
    sasToken: "XXXX"
    container: "demo"
    prefix: "fraud_detection"
    delimiter: "/"
```

**Comment by anna-geller** [comment]
bumped to P0 given prospects who need Azure ABS - @mgabelle given you're currently working with Azure, worth giving this one a look too 👍
